

SET DEFINE OFF;
--------------------------------------------------------------------------------
-- 1. PEOPLE / SPECIALIZATION
--------------------------------------------------------------------------------

CREATE TABLE person (
    person_id          NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    first_name         VARCHAR2(50) NOT NULL,
    last_name          VARCHAR2(50) NOT NULL,
    dob                DATE NOT NULL,
    present_address    VARCHAR2(255),
    permanent_address  VARCHAR2(255),

    CONSTRAINT pk_person PRIMARY KEY (person_id)
);

CREATE TABLE player (
    person_id          NUMBER(10),
    player_role        VARCHAR2(50) NOT NULL,
    gender             VARCHAR2(10) NOT NULL,
    education          VARCHAR2(100),
    family_background  VARCHAR2(2000),

    CONSTRAINT pk_player PRIMARY KEY (person_id),
    CONSTRAINT fk_player_person FOREIGN KEY (person_id)
        REFERENCES person(person_id),
    CONSTRAINT ck_player_gender CHECK (gender IN ('MALE', 'FEMALE'))
);

CREATE TABLE admin (
    person_id     NUMBER(10),
    designation   VARCHAR2(50) NOT NULL,
    department    VARCHAR2(50) NOT NULL,
    email         VARCHAR2(100) NOT NULL,
    joining_date  DATE NOT NULL,

    CONSTRAINT pk_admin PRIMARY KEY (person_id),
    CONSTRAINT fk_admin_person FOREIGN KEY (person_id)
        REFERENCES person(person_id),
    CONSTRAINT uq_admin_email UNIQUE (email),
    CONSTRAINT ck_admin_designation CHECK (
        designation IN (
            'Super Administrator',
            'Cricket Board Administrator',
            'Team Performance Manager',
            'Match Official / Scorer',
            'Integrity & Compliance Officer'
        )
    )
);

CREATE TABLE person_phone (
    person_id  NUMBER(10) NOT NULL,
    phone      VARCHAR2(20) NOT NULL,

    CONSTRAINT pk_person_phone PRIMARY KEY (person_id, phone),
    CONSTRAINT fk_person_phone_person FOREIGN KEY (person_id)
        REFERENCES person(person_id)
);

CREATE TABLE player_achievement (
    person_id    NUMBER(10) NOT NULL,
    achievement  VARCHAR2(255) NOT NULL,

    CONSTRAINT pk_player_achievement PRIMARY KEY (person_id, achievement),
    CONSTRAINT fk_player_achievement_player FOREIGN KEY (person_id)
        REFERENCES player(person_id)
);

--------------------------------------------------------------------------------
-- 2. AUTHENTICATION / APPLICATION ACCOUNT
--------------------------------------------------------------------------------

CREATE TABLE user_account (
    account_id      NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    person_id       NUMBER(10) NOT NULL,
    username        VARCHAR2(100) NOT NULL,
    password_hash   VARCHAR2(255) NOT NULL,
    account_status  VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_date    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    last_login      TIMESTAMP,

    CONSTRAINT pk_user_account PRIMARY KEY (account_id),
    CONSTRAINT fk_user_account_person FOREIGN KEY (person_id)
        REFERENCES person(person_id),
    CONSTRAINT uq_user_account_person UNIQUE (person_id),
    CONSTRAINT uq_user_account_username UNIQUE (username),
    CONSTRAINT ck_user_account_status CHECK (
        account_status IN ('ACTIVE', 'LOCKED', 'DISABLED')
    )
);

--------------------------------------------------------------------------------
-- 3. TEAM / PLAYER TEAM HISTORY / MENTORSHIP
--------------------------------------------------------------------------------

CREATE TABLE team (
    team_id           NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    team_name         VARCHAR2(100) NOT NULL,
    category          VARCHAR2(50) NOT NULL,
    franchise_owner   VARCHAR2(100),

    CONSTRAINT pk_team PRIMARY KEY (team_id)
);

CREATE TABLE plays_for (
    person_id  NUMBER(10) NOT NULL,
    team_id    NUMBER(10) NOT NULL,
    start_date DATE NOT NULL,
    end_date   DATE,

    CONSTRAINT pk_plays_for PRIMARY KEY (person_id, team_id, start_date),
    CONSTRAINT fk_plays_for_player FOREIGN KEY (person_id)
        REFERENCES player(person_id),
    CONSTRAINT fk_plays_for_team FOREIGN KEY (team_id)
        REFERENCES team(team_id),
    CONSTRAINT ck_plays_for_dates CHECK (
        end_date IS NULL OR end_date >= start_date
    )
);

CREATE TABLE mentors (
    junior_id     NUMBER(10) NOT NULL,
    mentor_id     NUMBER(10) NOT NULL,
    mentor_since  DATE NOT NULL,

    CONSTRAINT pk_mentors PRIMARY KEY (junior_id),
    CONSTRAINT fk_mentors_junior FOREIGN KEY (junior_id)
        REFERENCES player(person_id),
    CONSTRAINT fk_mentors_mentor FOREIGN KEY (mentor_id)
        REFERENCES player(person_id),
    CONSTRAINT ck_mentors_distinct CHECK (junior_id <> mentor_id)
);

--------------------------------------------------------------------------------
-- 4. PLAYER FITNESS / AVAILABILITY HISTORY
--------------------------------------------------------------------------------

CREATE TABLE player_fitness (
    fitness_record_id     NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    person_id             NUMBER(10) NOT NULL,
    injury_status         VARCHAR2(30) NOT NULL,
    recovery_status       VARCHAR2(50),
    expected_return_date  DATE,
    fitness_clearance     CHAR(1) DEFAULT 'N' NOT NULL,
    training_available    CHAR(1) DEFAULT 'N' NOT NULL,
    match_available       CHAR(1) DEFAULT 'N' NOT NULL,
    recorded_date         DATE DEFAULT SYSDATE NOT NULL,
    updated_by            NUMBER(10) NOT NULL,

    CONSTRAINT pk_player_fitness PRIMARY KEY (fitness_record_id),
    CONSTRAINT fk_player_fitness_player FOREIGN KEY (person_id)
        REFERENCES player(person_id),
    CONSTRAINT fk_player_fitness_admin FOREIGN KEY (updated_by)
        REFERENCES admin(person_id),
    CONSTRAINT ck_fitness_clearance CHECK (fitness_clearance IN ('Y', 'N')),
    CONSTRAINT ck_training_available CHECK (training_available IN ('Y', 'N')),
    CONSTRAINT ck_match_available CHECK (match_available IN ('Y', 'N')),
    CONSTRAINT ck_fitness_return_date CHECK (
        expected_return_date IS NULL OR expected_return_date >= recorded_date
    )
);

--------------------------------------------------------------------------------
-- 5. TOURNAMENT / MATCH / PARTICIPATING TEAMS
--------------------------------------------------------------------------------

CREATE TABLE tournament (
    tournament_id          NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    tournament_name        VARCHAR2(100) NOT NULL,
    tournament_tier_level  VARCHAR2(20) NOT NULL,
    season_year            NUMBER(4),

    CONSTRAINT pk_tournament PRIMARY KEY (tournament_id),
    CONSTRAINT ck_tournament_season_year CHECK (
        season_year IS NULL OR season_year BETWEEN 1800 AND 9999
    ),
    CONSTRAINT uq_tournament_name_season UNIQUE (tournament_name, season_year)
);

CREATE TABLE tournament_sponsor (
    tournament_id  NUMBER(10) NOT NULL,
    sponsor        VARCHAR2(100) NOT NULL,

    CONSTRAINT pk_tournament_sponsor PRIMARY KEY (tournament_id, sponsor),
    CONSTRAINT fk_tournament_sponsor_tournament FOREIGN KEY (tournament_id)
        REFERENCES tournament(tournament_id)
);

CREATE TABLE match (
    match_id        NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    tournament_id   NUMBER(10) NOT NULL,
    match_date      DATE NOT NULL,
    venue           VARCHAR2(100) NOT NULL,
    match_format    VARCHAR2(20) NOT NULL,
    match_status    VARCHAR2(20) DEFAULT 'SCHEDULED' NOT NULL,
    result          VARCHAR2(500),
    winner_team_id  NUMBER(10),

    CONSTRAINT pk_match PRIMARY KEY (match_id),
    CONSTRAINT fk_match_tournament FOREIGN KEY (tournament_id)
        REFERENCES tournament(tournament_id),
    CONSTRAINT fk_match_winner_team FOREIGN KEY (winner_team_id)
        REFERENCES team(team_id),
    CONSTRAINT ck_match_format CHECK (
        match_format IN ('Test', 'ODI', 'T20', 'First-Class', 'List A', 'Domestic T20')
    ),
    CONSTRAINT ck_match_status CHECK (
        match_status IN ('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')
    )
);

CREATE TABLE includes (
    match_id  NUMBER(10) NOT NULL,
    team_id   NUMBER(10) NOT NULL,

    CONSTRAINT pk_includes PRIMARY KEY (match_id, team_id),
    CONSTRAINT fk_includes_match FOREIGN KEY (match_id)
        REFERENCES match(match_id),
    CONSTRAINT fk_includes_team FOREIGN KEY (team_id)
        REFERENCES team(team_id)
);

--------------------------------------------------------------------------------
-- 6. CAREER RECORD AND FORMAT SUMMARIES
--------------------------------------------------------------------------------

CREATE TABLE career_record (
    record_id       NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    person_id       NUMBER(10) NOT NULL,
    team_id         NUMBER(10) NOT NULL,
    tier_level      VARCHAR2(20) NOT NULL,
    location_type   VARCHAR2(20) NOT NULL,
    matches_played  NUMBER(10) DEFAULT 0 NOT NULL,
    start_date      DATE NOT NULL,
    end_date        DATE,

    CONSTRAINT pk_career_record PRIMARY KEY (record_id),
    CONSTRAINT fk_career_record_player FOREIGN KEY (person_id)
        REFERENCES player(person_id),
    CONSTRAINT fk_career_record_team FOREIGN KEY (team_id)
        REFERENCES team(team_id),
    CONSTRAINT ck_career_matches CHECK (matches_played >= 0),
    CONSTRAINT ck_career_dates CHECK (
        end_date IS NULL OR end_date >= start_date
    )
);

CREATE TABLE batting_summary (
    bat_summary_id  NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    record_id       NUMBER(10) NOT NULL,
    total_runs      NUMBER(10) NOT NULL,
    batting_avg     NUMBER(7,2) NOT NULL,
    strike_rate     NUMBER(7,2) NOT NULL,
    highest_score   NUMBER(10) NOT NULL,
    format          VARCHAR2(20) NOT NULL,

    CONSTRAINT pk_batting_summary PRIMARY KEY (bat_summary_id),
    CONSTRAINT fk_batting_summary_record FOREIGN KEY (record_id)
        REFERENCES career_record(record_id),
    CONSTRAINT uq_batting_summary_record_format UNIQUE (record_id, format),
    CONSTRAINT ck_batting_summary_values CHECK (
        total_runs >= 0 AND
        batting_avg >= 0 AND
        strike_rate >= 0 AND
        highest_score >= 0
    ),
    CONSTRAINT ck_batting_summary_format CHECK (
        format IN ('Test', 'ODI', 'T20', 'First-Class', 'List A', 'Domestic T20')
    )
);

CREATE TABLE bowling_summary (
    bowl_summary_id       NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    record_id             NUMBER(10) NOT NULL,
    total_wickets         NUMBER(10) NOT NULL,
    bowling_avg           NUMBER(7,2) NOT NULL,
    best_bowling_figures  VARCHAR2(20) NOT NULL,
    economy_rate          NUMBER(7,2) NOT NULL,
    format                VARCHAR2(20) NOT NULL,

    CONSTRAINT pk_bowling_summary PRIMARY KEY (bowl_summary_id),
    CONSTRAINT fk_bowling_summary_record FOREIGN KEY (record_id)
        REFERENCES career_record(record_id),
    CONSTRAINT uq_bowling_summary_record_format UNIQUE (record_id, format),
    CONSTRAINT ck_bowling_summary_values CHECK (
        total_wickets >= 0 AND
        bowling_avg >= 0 AND
        economy_rate >= 0
    ),
    CONSTRAINT ck_bowling_summary_format CHECK (
        format IN ('Test', 'ODI', 'T20', 'First-Class', 'List A', 'Domestic T20')
    )
);

CREATE TABLE fielding_summary (
    field_summary_id          NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    record_id                 NUMBER(10) NOT NULL,
    total_catches             NUMBER(10) NOT NULL,
    total_stumpings           NUMBER(10) NOT NULL,
    total_runouts             NUMBER(10) NOT NULL,
    most_dismissals_in_match  NUMBER(10) NOT NULL,
    format                    VARCHAR2(20) NOT NULL,

    CONSTRAINT pk_fielding_summary PRIMARY KEY (field_summary_id),
    CONSTRAINT fk_fielding_summary_record FOREIGN KEY (record_id)
        REFERENCES career_record(record_id),
    CONSTRAINT uq_fielding_summary_record_format UNIQUE (record_id, format),
    CONSTRAINT ck_fielding_summary_values CHECK (
        total_catches >= 0 AND
        total_stumpings >= 0 AND
        total_runouts >= 0 AND
        most_dismissals_in_match >= 0
    ),
    CONSTRAINT ck_fielding_summary_format CHECK (
        format IN ('Test', 'ODI', 'T20', 'First-Class', 'List A', 'Domestic T20')
    )
);

--------------------------------------------------------------------------------
-- 7. MATCH PERFORMANCE
--------------------------------------------------------------------------------

CREATE TABLE batting_performance (
    bat_stat_id      NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    bat_summary_id   NUMBER(10) NOT NULL,
    match_id         NUMBER(10) NOT NULL,
    runs_scored      NUMBER(10) NOT NULL,
    balls_faced      NUMBER(10) NOT NULL,
    strike_rate      NUMBER(7,2) NOT NULL,
    dismissal_type   VARCHAR2(50),

    CONSTRAINT pk_batting_performance PRIMARY KEY (bat_stat_id),
    CONSTRAINT fk_batting_performance_summary FOREIGN KEY (bat_summary_id)
        REFERENCES batting_summary(bat_summary_id),
    CONSTRAINT fk_batting_performance_match FOREIGN KEY (match_id)
        REFERENCES match(match_id),
    CONSTRAINT uq_batting_perf_match_summary UNIQUE (match_id, bat_summary_id),
    CONSTRAINT ck_batting_performance_values CHECK (
        runs_scored >= 0 AND
        balls_faced >= 0 AND
        strike_rate >= 0
    )
);

CREATE TABLE bowling_performance (
    bowl_stat_id     NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    bowl_summary_id  NUMBER(10) NOT NULL,
    match_id         NUMBER(10) NOT NULL,
    wickets_taken    NUMBER(10) NOT NULL,
    balls_bowled     NUMBER(10) NOT NULL,
    runs_conceded    NUMBER(10) NOT NULL,
    economy_rate     NUMBER(7,2) NOT NULL,

    CONSTRAINT pk_bowling_performance PRIMARY KEY (bowl_stat_id),
    CONSTRAINT fk_bowling_performance_summary FOREIGN KEY (bowl_summary_id)
        REFERENCES bowling_summary(bowl_summary_id),
    CONSTRAINT fk_bowling_performance_match FOREIGN KEY (match_id)
        REFERENCES match(match_id),
    CONSTRAINT uq_bowling_perf_match_summary UNIQUE (match_id, bowl_summary_id),
    CONSTRAINT ck_bowling_performance_values CHECK (
        wickets_taken >= 0 AND
        balls_bowled >= 0 AND
        runs_conceded >= 0 AND
        economy_rate >= 0
    )
);

CREATE TABLE fielding_performance (
    field_stat_id     NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    field_summary_id  NUMBER(10) NOT NULL,
    match_id          NUMBER(10) NOT NULL,
    catches           NUMBER(10) NOT NULL,
    stumpings         NUMBER(10) NOT NULL,
    runs_out_direct   NUMBER(10) NOT NULL,
    byes_conceded     NUMBER(10) NOT NULL,

    CONSTRAINT pk_fielding_performance PRIMARY KEY (field_stat_id),
    CONSTRAINT fk_fielding_performance_summary FOREIGN KEY (field_summary_id)
        REFERENCES fielding_summary(field_summary_id),
    CONSTRAINT fk_fielding_performance_match FOREIGN KEY (match_id)
        REFERENCES match(match_id),
    CONSTRAINT uq_fielding_perf_match_summary UNIQUE (match_id, field_summary_id),
    CONSTRAINT ck_fielding_performance_values CHECK (
        catches >= 0 AND
        stumpings >= 0 AND
        runs_out_direct >= 0 AND
        byes_conceded >= 0
    )
);

--------------------------------------------------------------------------------
-- 8. INTEGRITY / DISCIPLINARY MANAGEMENT
--------------------------------------------------------------------------------

CREATE TABLE rulebook (
    rule_id     NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    clause_no   VARCHAR2(20) NOT NULL,
    category    VARCHAR2(50) NOT NULL,

    CONSTRAINT pk_rulebook PRIMARY KEY (rule_id),
    CONSTRAINT uq_rulebook_clause UNIQUE (category, clause_no)
);

CREATE TABLE complaint (
    complaint_id     NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    source_type      VARCHAR2(50) NOT NULL,
    date_received    DATE DEFAULT SYSDATE NOT NULL,
    description      VARCHAR2(2000) NOT NULL,
    misconduct_type  VARCHAR2(100),

    CONSTRAINT pk_complaint PRIMARY KEY (complaint_id)
);

CREATE TABLE case_record (
    case_id                NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    status                 VARCHAR2(30) DEFAULT 'OPEN' NOT NULL,
    involvement_type       VARCHAR2(50),
    date_opened            DATE DEFAULT SYSDATE NOT NULL,
    referral_status        VARCHAR2(20) DEFAULT 'NOT_REFERRED' NOT NULL,
    referred_to_authority  VARCHAR2(200),

    CONSTRAINT pk_case_record PRIMARY KEY (case_id),
    CONSTRAINT ck_case_status CHECK (
        status IN ('OPEN', 'UNDER_INVESTIGATION', 'REFERRED', 'CLOSED')
    ),
    CONSTRAINT ck_case_referral_status CHECK (
        referral_status IN ('NOT_REFERRED', 'REFERRED')
    ),
    CONSTRAINT ck_case_referral_consistency CHECK (
        (referral_status = 'NOT_REFERRED' AND referred_to_authority IS NULL)
        OR
        (referral_status = 'REFERRED' AND referred_to_authority IS NOT NULL)
    ),
    CONSTRAINT ck_case_referred_state CHECK (
        status <> 'REFERRED' OR referral_status = 'REFERRED'
    )
);

/*
  Project rule: ONLY PLAYER can participate in a case.
  The FK intentionally targets PLAYER, not PERSON.
*/
CREATE TABLE involves_in (
    person_id  NUMBER(10) NOT NULL,
    case_id    NUMBER(10) NOT NULL,

    CONSTRAINT pk_involves_in PRIMARY KEY (person_id, case_id),
    CONSTRAINT fk_involves_in_player FOREIGN KEY (person_id)
        REFERENCES player(person_id),
    CONSTRAINT fk_involves_in_case FOREIGN KEY (case_id)
        REFERENCES case_record(case_id)
);

CREATE TABLE investigates (
    person_id  NUMBER(10) NOT NULL,
    case_id    NUMBER(10) NOT NULL,
    admin_id   NUMBER(10) NOT NULL,

    CONSTRAINT pk_investigates PRIMARY KEY (person_id, case_id),
    CONSTRAINT fk_investigates_involvement FOREIGN KEY (person_id, case_id)
        REFERENCES involves_in(person_id, case_id),
    CONSTRAINT fk_investigates_admin FOREIGN KEY (admin_id)
        REFERENCES admin(person_id)
);

CREATE TABLE violates (
    case_id  NUMBER(10) NOT NULL,
    rule_id  NUMBER(10) NOT NULL,

    CONSTRAINT pk_violates PRIMARY KEY (case_id, rule_id),
    CONSTRAINT fk_violates_case FOREIGN KEY (case_id)
        REFERENCES case_record(case_id),
    CONSTRAINT fk_violates_rule FOREIGN KEY (rule_id)
        REFERENCES rulebook(rule_id)
);

CREATE TABLE source_of (
    case_id       NUMBER(10) NOT NULL,
    complaint_id  NUMBER(10) NOT NULL,

    CONSTRAINT pk_source_of PRIMARY KEY (case_id, complaint_id),
    CONSTRAINT fk_source_of_case FOREIGN KEY (case_id)
        REFERENCES case_record(case_id),
    CONSTRAINT fk_source_of_complaint FOREIGN KEY (complaint_id)
        REFERENCES complaint(complaint_id)
);

CREATE TABLE evidence (
    case_id         NUMBER(10) NOT NULL,
    evidence_no     NUMBER(10) NOT NULL,
    description     VARCHAR2(2000) NOT NULL,
    collected_date  DATE NOT NULL,

    CONSTRAINT pk_evidence PRIMARY KEY (case_id, evidence_no),
    CONSTRAINT fk_evidence_case FOREIGN KEY (case_id)
        REFERENCES case_record(case_id),
    CONSTRAINT ck_evidence_number CHECK (evidence_no > 0)
);

--------------------------------------------------------------------------------
-- 9. ADMIN OBSERVATION OF PLAYER IN A MATCH (TERNARY RELATIONSHIP)
--------------------------------------------------------------------------------

CREATE TABLE observes (
    admin_id          NUMBER(10) NOT NULL,
    player_id         NUMBER(10) NOT NULL,
    match_id          NUMBER(10) NOT NULL,
    observation_date  DATE NOT NULL,
    remarks           VARCHAR2(2000),

    CONSTRAINT pk_observes PRIMARY KEY
        (admin_id, player_id, match_id, observation_date),
    CONSTRAINT fk_observes_admin FOREIGN KEY (admin_id)
        REFERENCES admin(person_id),
    CONSTRAINT fk_observes_player FOREIGN KEY (player_id)
        REFERENCES player(person_id),
    CONSTRAINT fk_observes_match FOREIGN KEY (match_id)
        REFERENCES match(match_id)
);

--------------------------------------------------------------------------------
-- 10. AUDIT SUPPORT
--------------------------------------------------------------------------------

CREATE TABLE audit_log (
    audit_id           NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    actor_person_id    NUMBER(10),
    entity_name        VARCHAR2(50) NOT NULL,
    record_identifier  VARCHAR2(200) NOT NULL,
    operation          VARCHAR2(10) NOT NULL,
    action_timestamp   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    old_values         CLOB,
    new_values         CLOB,

    CONSTRAINT pk_audit_log PRIMARY KEY (audit_id),
    CONSTRAINT fk_audit_log_actor FOREIGN KEY (actor_person_id)
        REFERENCES person(person_id),
    CONSTRAINT ck_audit_operation CHECK (
        operation IN ('INSERT', 'UPDATE', 'DELETE')
    )
);

