export type ModuleStatus = "implemented" | "isolated" | "deferred";

export const moduleStatus = {
  rootRedirect: { route: "/", status: "isolated" },
  signIn: { route: "/sign-in", status: "isolated" },
  superAdminDashboard: { route: "/super-admin/dashboard", status: "implemented" },
  boardAdminDashboard: { route: "/board-admin/dashboard", status: "implemented" },
  performanceDashboard: { route: "/performance/dashboard", status: "implemented" },
  matchOfficialDashboard: { route: "/match-official/dashboard", status: "implemented" },
  integrityDashboard: { route: "/integrity/dashboard", status: "implemented" },
  playerDashboard: { route: "/player/dashboard", status: "implemented" },
  playerRegistry: { route: "/players", status: "implemented" },
  playerProfile: { route: "/players/[playerId]", status: "implemented" },
  registerPlayer: { route: "/players/new", status: "implemented" },
  editPlayer: { route: "/players/[playerId]/edit", status: "implemented" },
  teamRegistry: { route: "/teams", status: "implemented" },
  teamDetails: { route: "/teams/[teamId]", status: "implemented" },
  tournamentRegistry: { route: "/tournaments", status: "implemented" },
  tournamentDetails: { route: "/tournaments/[tournamentId]", status: "implemented" },
  matchRegistry: { route: "/matches", status: "implemented" },
  matchDetails: { route: "/matches/[matchId]", status: "implemented" },
  performanceRegistry: { route: "/performance/players", status: "implemented" },
  playerPerformance: { route: "/performance/players/[playerId]", status: "implemented" },
  complaintRegistry: { route: "/integrity/complaints", status: "implemented" },
  complaintDetails: { route: "/integrity/complaints/[complaintId]", status: "implemented" },
  caseRegistry: { route: "/integrity/cases", status: "implemented" },
  caseDetails: { route: "/integrity/cases/[caseId]", status: "implemented" },
  rulebookRegistry: { route: "/integrity/rulebook", status: "implemented" },
  rulebookDetails: { route: "/integrity/rulebook/[ruleId]", status: "implemented" },
  reports: { status: "deferred" },
  notifications: { status: "deferred" },
  userManagement: { status: "deferred" },
  roleEditor: { status: "deferred" },
  systemLogs: { status: "deferred" },
  documentManagement: { status: "deferred" },
  fitnessManagement: { status: "deferred" },
  trainingManagement: { status: "deferred" },
  selectionWorkflows: { status: "deferred" },
} as const satisfies Record<string, { route?: string; status: ModuleStatus }>;
